FASTIOT_BROKER_HOST = 'FASTIOT_BROKER_HOST'
FASTIOT_BROKER_PORT = 'FASTIOT_BROKER_PORT'
FASTIOT_BROKER_DEFAULT_TIMEOUT = 'FASTIOT_BROKER_DEFAULT_TIMEOUT'
FASTIOT_BROKER_STREAM_TIMEOUT = 'FASTIOT_BROKER_STREAM_TIMEOUT'


FASTIOT_MONGO_DB_HOST = 'FASTIOT_MONGO_DB_HOST'
FASTIOT_MONGO_DB_PORT = 'FASTIOT_MONGO_DB_PORT'
FASTIOT_MONGO_DB_USER = 'FASTIOT_MONGO_DB_USER'
FASTIOT_MONGO_DB_PASSWORD = 'FASTIOT_MONGO_DB_PASSWORD'
FASTIOT_MONGO_DB_AUTH_SOURCE = 'FASTIOT_MONGO_DB_AUTH_SOURCE'
FASTIOT_MONGO_DB_NAME = 'FASTIOT_MONGO_DB_NAME'


FASTIOT_CONFIG_DIR = 'FASTIOT_CONFIG_DIR'
