""" WARNING: THIS FILE HAS BEEN AUTOGENERATED DO NOT EDIT IT!!!

This file sets the environment variables for infrastructure service ports.
The contents are generated together with the docker-compose containing the services to be started for integration tests.
"""
import os


def set_test_environment():
    env_vars = {'FASTIOT_INFLUX_DB_BUCKET': 'sensors',
                'FASTIOT_INFLUX_DB_HOST': 'localhost',
                'FASTIOT_INFLUX_DB_MODE': 'setup',
                'FASTIOT_INFLUX_DB_ORG': 'IVVDD',
                'FASTIOT_INFLUX_DB_PASSWORD': 'mf9ZXfeLKuaL3HL7w',
                'FASTIOT_INFLUX_DB_PORT': '8086',
                'FASTIOT_INFLUX_DB_TOKEN': '12345',
                'FASTIOT_INFLUX_DB_USER': 'influx_db_admin',
                'FASTIOT_MARIA_DB_HOST': 'localhost',
                'FASTIOT_MARIA_DB_PASSWORD': '12345',
                'FASTIOT_MARIA_DB_PORT': '3306',
                'FASTIOT_MONGO_DB_HOST': 'localhost',
                'FASTIOT_MONGO_DB_PASSWORD': '12345',
                'FASTIOT_MONGO_DB_PORT': '27017',
                'FASTIOT_MONGO_DB_USER': 'root',
                'FASTIOT_NATS_HOST': 'localhost',
                'FASTIOT_NATS_PORT': '4222',
                'FASTIOT_TIME_SCALE_DB_DATABASE': 'fastiot_db',
                'FASTIOT_TIME_SCALE_DB_HOST': 'localhost',
                'FASTIOT_TIME_SCALE_DB_PASSWORD': '12345',
                'FASTIOT_TIME_SCALE_DB_PORT': '5432',
                'FASTIOT_TIME_SCALE_DB_USER': 'postgres'}
    for name, value in env_vars.items():
        os.environ[name] = str(value)
